# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d0d380ee78e4c76556c09d404916f58"
name = "restockpulse-app"
application_url = "https://restockpulse-app.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory-levels-update"
  topics = [ "inventory_levels/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://restockpulse-app.fly.dev/auth/callback",
  "https://restockpulse-app.fly.dev/auth/shopify/callback",
  "https://restockpulse-app.fly.dev/api/auth/callback"
]
